### ISSUE TITLE
Nodejs8.10 not supported

### ISSUE THREAD

**Issue by denis-spitsin** [aws-samples/amazon-efs-tutorial#10]
We have an issue with template. Nodejs8.10 is not supported anymore:
`The runtime parameter of nodejs8.10 is no longer supported for creating or updating AWS Lambda functions. We recommend you use the new runtime (nodejs12.x) while creating or updating functions. (Service: AWSLambdaInternal; Status Code: 400; Error Code: InvalidParameterValueException; Request ID: 115ba1c6-c130-43ba-9edc-ae40e8f0a8f6)`

**Comment by darrylsosborne** [comment]
Updated Lambda function to support nodejs12.x.
