### ISSUE TITLE
DataSync Resources not created after launching the stack

### ISSUE THREAD

**Issue by purnareddy** [aws-samples/amazon-efs-tutorial#5]

**Comment by purnareddy** [comment]
Below is the error: 

DataSync: Execute       Creating datasync resources
 DataSync: Execute       Self-activating and creating agent in XHTML for <?xml
 DataSync: Error         Failed to self-activate or create agent in XHTML for <?xml
 DataSync: Error         Failed to create datasync resources

**Comment by darrylsosborne** [comment]
@purnareddy Failures during "self-activating and creating agent" are typically caused by the source security group id selected doesn't allow inbound HTTP (TCP 80) from the Internet (0.0.0.0/0).  Please verify the source security group inbound rules are setup correctly - refer to the user guide, page 6, #5 - https://s3.amazonaws.com/aws-us-east-1/amazon-efs-tutorial/in-cloud-transfer/datasync_in-cloud_transfer_quick_start_scheduler_ug.pdf

**Comment by purnareddy** [comment]
@darrylsosborne  Source security group already allows inbound HTTP (TCP 80) from 0.0.0.0/0. Data Sync agent is hosted in a private subnet though. I hope this should be fine.
Also, both the source & destination EFS are in private subnets? I did a VPC Peering between source & destination EFS for network communication.

**Comment by darrylsosborne** [comment]
@purnareddy DataSync establishes a TLS 1.2 connection between the DataSync in-cloud agent running on EC2, which connects to the source file system, and the DataSync service that connects to the destination file system. Establishing a VPC peering connection is not necessary. The DataSync in-cloud agent needs access to these endpoints:

# API (TCP 443)
  datasync.$region.amazonaws.com
                
# Data transfer (TCP 443)                
  $taskId.datasync-dp.$region.amazonaws.com
  cp.datasync.$region.amazonaws.com
  cp-sync.$region.amazonaws.com
               
# Agent updates (TCP 443)
  repo.$region.amazonaws.com                
  repo.default.amazonaws.com
  packages.$region.amazonaws.com
                
# NTP (UDP 123)                
  0.amazon.pool.ntp.org
  1.amazon.pool.ntp.org
  2.amazon.pool.ntp.org
  3.amazon.pool.ntp.org

# Support channel (TCP 22)
  54.201.223.107

# Agent activation only. This endpoint can be blocked after activation (TCP 443)
  https://d4kdq0yaxexbo.cloudfront.net/
  activation.datasync.$region.amazonaws.com
  activation-sync.$region.amazonaws.com

More information is available here - https://github.com/aws-samples/amazon-efs-tutorial/issues/5

**Comment by purnareddy** [comment]
@darrylsosborne Datasync agent has access to all these ports but still see that error. Any prerequisite that the agent should be in a public subnet? Right now, it is sitting behind a NAT gateway.

**Comment by darrylsosborne** [comment]
@purnareddy The source subnet needs to be public and the subnet must have "Auto-assign IPv4" enabled, so a public IPv4 address is automatically assigned with the DataSync agent instance is launched. I'll look at making a change to the template to remove the "Auto-assign IPv4" requirement and just have the instance automatically get a public IP at launch (I can get this out later today). I'll also look at what it would take to move this into a private subnet (this may take longer).

**Comment by darrylsosborne** [comment]
@purnareddy You'll need to delete the CloudFormation stack and create it again. I also updated the template do automatically assign a public IP during instance launch, so no longer do you need to enable "Auto-assign IPv4" at the subnet level.

**Comment by darrylsosborne** [comment]
@purnareddy Support for running the DataSync agent in a private subnet will be available later today.

**Comment by purnareddy** [comment]
@darrylsosborne Thank you! I will deploy the solution & test when ready.

**Comment by darrylsosborne** [comment]
@purnareddy Sorry... ran into an issue but I think its resolved. I'll have something by the morning.

**Comment by darrylsosborne** [comment]
@purnareddy Just published an update. Now you can use a private subnet as the source subnet, as long as the source subnet has a route to the datasync endpoints (i.e. NAT gateway, etc.).  Also, the DataSync in-cloud agent no longer requires to have a public IP address and a public IPv4 address is not automatically assigned to the instance.

**Comment by purnareddy** [comment]
@darrylsosborne Works fine now. Does the datasync agent has to be up and running all the time. I wanted to do a filesync every 24 hours. It doesn't make sense to keep it running all the time. Can we update the solution to automatically bring the data sync agent up during the maintenance window defined. And after the task execution, just shut it down?

**Comment by darrylsosborne** [comment]
@purnareddy Right now its designed to stay up. I'll have to look at making a larger design change to bring up the agent during the maintenance window. This will likely take some time to develop, test, and publish to the repo.

**Comment by purnareddy** [comment]
@darrylsosborne Okay, sounds good. Closing this one for now. Please let us know when you plan on releasing the next version.
