### ISSUE TITLE
Subsequent data sync executions fail. Error: Sync verification failed due to a difference in metadata of one or more files

### ISSUE THREAD

**Issue by purnareddy** [aws-samples/amazon-efs-tutorial#6]

**Comment by darrylsosborne** [comment]
@purnareddy If the source directory is changing during task execution, the sync verification will error. If on-going changes will be made to the source directory during task execution, it is best to go into the DataSync console and edit the task execution settings to disable verification. Once that's set at the task level all subsequent task executions will not run a verification. During a period when no changes will be made during a task execution, you can enable verification to verify source and destination directories. You can read more about how DataSync works, including verification, in the DataSync User Guide - https://docs.aws.amazon.com/datasync/latest/userguide/how-datasync-works.html#how-verifying-works

**Comment by purnareddy** [comment]
@darrylsosborne My source directory continuously puts files. I disabled verification and it works fine. Thanks for the info.
