### ISSUE TITLE
Monitoring: "Throughput Utilization" should use AVG of PermittedThroughput

### ISSUE THREAD

**Issue by vincer** [aws-samples/amazon-efs-tutorial#7]
The description says to use SUM. With SUM the metric will not scale with the graph's period properly and will only be valid when period=1 minute.  By using AVG on PermittedThroughput, the period can be changed to anything.

https://github.com/aws-samples/amazon-efs-tutorial/tree/master/monitoring#throughput-utilization

**Comment by darrylsosborne** [comment]
Updated Permitted Throughput command to use "AVG" statistic
