### ISSUE TITLE
Incorrect 'fpart' option in performance tutorial

### ISSUE THREAD

**Issue by zxkane** [aws-samples/amazon-efs-tutorial#8]
In section [5.9](https://github.com/aws-samples/amazon-efs-tutorial/blob/master/performance/README.md#59--transfer-files-from-ebs-to-efs-using-fpart--cpio--gnu-parallel) uses below `fpart` command to create file list,

```
time /usr/local/bin/fpart -Z -n 1 -o /home/ec2-user/fpart-files-to-transfer .
```

Option `-Z` is not valid option of fpart, the correct one should be `-z`.

**Comment by darrylsosborne** [comment]
Updated fpart script to use the "-z" option.
